# Generated by Django 5.0.1 on 2025-01-12 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteAduanal',
            fields=[
                ('patente', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('razon_social', models.CharField(max_length=80, null=True)),
                ('rfc', models.CharField(max_length=20, null=True)),
                ('curp', models.CharField(max_length=18, null=True)),
                ('direccion1', models.CharField(max_length=60, null=True)),
                ('direccion2', models.CharField(max_length=60, null=True)),
                ('direccion3', models.CharField(max_length=60, null=True)),
                ('serie', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agentes Aduanales',
            },
        ),
        migrations.CreateModel(
            name='ClavePedimento',
            fields=[
                ('cve_pedimento', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120, null=True)),
                ('importacion', models.BooleanField()),
                ('exportacion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AduanaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_aduana', models.CharField(max_length=2)),
                ('cve_seccion', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=60, null=True)),
            ],
            options={
                'unique_together': {('cve_aduana', 'cve_seccion')},
            },
        ),
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('num_pedimento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo_operacion', models.IntegerField(choices=[(1, 'Importación'), (2, 'Exportación')])),
                ('fecha_entrada', models.DateField()),
                ('fecha_pago', models.DateField(null=True)),
                ('aduana_seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_app.aduanaseccion')),
                ('clave_pedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_app.clavepedimento')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_app.agenteaduanal')),
            ],
        ),
    ]
